micronaut:
  application:
    name: catalog
    instance:
      # required if running multiple instances, for collisions avoidance
      id: ${random.shortuuid}
  server:
    port: 8081

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

tracing:
  zipkin:
    enabled: true
    http:
      urls:
        - "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
    sampler:
      probability: 1

kafka:
  bootstrap:
    servers: localhost:9092
