micronaut:
  application:
    name: shop

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**


catalog:
  books:
    retry:
      attempts: 4
      multiplier: 1
      delay: 2s
